{{- if .Values.cronjobs.consulUpdater.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "proxysql.fullname" . }}-consul-updater
spec:
  schedule: "{{ .Values.cronjobs.consulUpdater.schedule }}"
  suspend: false
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: consul-updater
              image: {{ .Values.cronjobs.consulUpdater.image }}:{{ .Values.cronjobs.consulUpdater.tag }}
              imagePullPolicy: IfNotPresent
              command: ["/bin/bash","-c"]
              env:
                - name: CONSUL_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: consul-token-write
                      key: token
                - name: CONSUL_SERVICE
                  value: {{ .Values.consul.host }}
              args:
                - |
                  until curl -fsI http://localhost:15021/healthz/ready; do echo \"Waiting for Sidecar...\"; sleep 3; done;
                  echo \"Sidecar available. Running the command...\";
                  python3 dump_consul_data.py && python3 generate_proxysql_credentials.py && python3 write_proxysql_credentials.py;
                  x=$(echo $?); curl -fsI -X POST http://localhost:15020/quitquitquit && exit $x
          restartPolicy: OnFailure
---
{{- end }}
