apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "proxysql.fullname" . }}
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- $mysqlPort := .Values.proxysql.mysql.port | default "mysql" }}
    {{ range .Values.service.ports -}}
    - port: {{ . }}
      targetPort: {{ $mysqlPort }}
      protocol: TCP
      name: "mysql-{{ . }}"
    {{ end }}
  selector:
    {{- include "proxysql.selectorLabels" . | nindent 4 }}
